port: 8080
mysql:
  host: e6156-db.clxkc1uvbaql.us-east-1.rds.amazonaws.com
  port: 3306
  username: dbuser
  password: dbuserdbuser
  dbname: hw1
oauth:
  clientID: 979573387363-dt8mhvvau8kebm1102pd1uo7oq54t4u2.apps.googleusercontent.com
  clientSecret: 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
  oauthStateString: thisshouldberandom